apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodeapp
  namespace: default
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: nodeapp
  template: 
    metadata:
      labels:
        app: nodeapp
    spec: 
      containers:
      - name: nodeapp
        image: ghcr.io/ukpagrace/nodeapp:2157b3ce5046e2e1368b04b06769694635bfc155
        imagePullPolicy: Always
        ports:
        - containerPort: 3000